// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(rustylibFFI)
    import rustylibFFI
#endif

private extension RustBuffer {
    /// Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_rustylib_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    /// Frees the buffer in place.
    /// The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_rustylib_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

/// Reads an integer at the current offset, in big-endian order, and advances
/// the offset on success. Throws if reading the integer would move the
/// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

/// Reads an arbitrary number of bytes, to be used to read
/// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

/// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

/// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

/// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S: Sequence>(_ writer: inout [UInt8], _ byteArr: S) where S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

/// Writes an integer in big-endian order.
///
/// Warning: make sure what you are trying to write
/// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

/// Protocol for types that transfer other types across the FFI. This is
/// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

/// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

/// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
/// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

/// An error type for FFI errors. These errors occur at the UniFFI level, not
/// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

// Public interface members begin here.

private struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

private struct FfiConverterBool: FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

public struct SerieCommitDetail {
    public var commit: SerieCommitSummary
    public var changes: [SerieFileChange]

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(commit: SerieCommitSummary, changes: [SerieFileChange]) {
        self.commit = commit
        self.changes = changes
    }
}

extension SerieCommitDetail: Equatable, Hashable {
    public static func == (lhs: SerieCommitDetail, rhs: SerieCommitDetail) -> Bool {
        if lhs.commit != rhs.commit {
            return false
        }
        if lhs.changes != rhs.changes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(commit)
        hasher.combine(changes)
    }
}

public struct FfiConverterTypeSerieCommitDetail: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SerieCommitDetail {
        return
            try SerieCommitDetail(
                commit: FfiConverterTypeSerieCommitSummary.read(from: &buf),
                changes: FfiConverterSequenceTypeSerieFileChange.read(from: &buf)
            )
    }

    public static func write(_ value: SerieCommitDetail, into buf: inout [UInt8]) {
        FfiConverterTypeSerieCommitSummary.write(value.commit, into: &buf)
        FfiConverterSequenceTypeSerieFileChange.write(value.changes, into: &buf)
    }
}

public func FfiConverterTypeSerieCommitDetail_lift(_ buf: RustBuffer) throws -> SerieCommitDetail {
    return try FfiConverterTypeSerieCommitDetail.lift(buf)
}

public func FfiConverterTypeSerieCommitDetail_lower(_ value: SerieCommitDetail) -> RustBuffer {
    return FfiConverterTypeSerieCommitDetail.lower(value)
}

public struct SerieCommitSummary {
    public var hash: String
    public var shortHash: String
    public var authorName: String
    public var authorEmail: String
    public var authorDate: String
    public var committerName: String
    public var committerEmail: String
    public var committerDate: String
    public var subject: String
    public var body: String
    public var parents: [String]
    public var kind: SerieCommitKind
    public var refs: [SerieRepositoryRef]

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(hash: String, shortHash: String, authorName: String, authorEmail: String, authorDate: String, committerName: String, committerEmail: String, committerDate: String, subject: String, body: String, parents: [String], kind: SerieCommitKind, refs: [SerieRepositoryRef]) {
        self.hash = hash
        self.shortHash = shortHash
        self.authorName = authorName
        self.authorEmail = authorEmail
        self.authorDate = authorDate
        self.committerName = committerName
        self.committerEmail = committerEmail
        self.committerDate = committerDate
        self.subject = subject
        self.body = body
        self.parents = parents
        self.kind = kind
        self.refs = refs
    }
}

extension SerieCommitSummary: Equatable, Hashable {
    public static func == (lhs: SerieCommitSummary, rhs: SerieCommitSummary) -> Bool {
        if lhs.hash != rhs.hash {
            return false
        }
        if lhs.shortHash != rhs.shortHash {
            return false
        }
        if lhs.authorName != rhs.authorName {
            return false
        }
        if lhs.authorEmail != rhs.authorEmail {
            return false
        }
        if lhs.authorDate != rhs.authorDate {
            return false
        }
        if lhs.committerName != rhs.committerName {
            return false
        }
        if lhs.committerEmail != rhs.committerEmail {
            return false
        }
        if lhs.committerDate != rhs.committerDate {
            return false
        }
        if lhs.subject != rhs.subject {
            return false
        }
        if lhs.body != rhs.body {
            return false
        }
        if lhs.parents != rhs.parents {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.refs != rhs.refs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(hash)
        hasher.combine(shortHash)
        hasher.combine(authorName)
        hasher.combine(authorEmail)
        hasher.combine(authorDate)
        hasher.combine(committerName)
        hasher.combine(committerEmail)
        hasher.combine(committerDate)
        hasher.combine(subject)
        hasher.combine(body)
        hasher.combine(parents)
        hasher.combine(kind)
        hasher.combine(refs)
    }
}

public struct FfiConverterTypeSerieCommitSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SerieCommitSummary {
        return
            try SerieCommitSummary(
                hash: FfiConverterString.read(from: &buf),
                shortHash: FfiConverterString.read(from: &buf),
                authorName: FfiConverterString.read(from: &buf),
                authorEmail: FfiConverterString.read(from: &buf),
                authorDate: FfiConverterString.read(from: &buf),
                committerName: FfiConverterString.read(from: &buf),
                committerEmail: FfiConverterString.read(from: &buf),
                committerDate: FfiConverterString.read(from: &buf),
                subject: FfiConverterString.read(from: &buf),
                body: FfiConverterString.read(from: &buf),
                parents: FfiConverterSequenceString.read(from: &buf),
                kind: FfiConverterTypeSerieCommitKind.read(from: &buf),
                refs: FfiConverterSequenceTypeSerieRepositoryRef.read(from: &buf)
            )
    }

    public static func write(_ value: SerieCommitSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.hash, into: &buf)
        FfiConverterString.write(value.shortHash, into: &buf)
        FfiConverterString.write(value.authorName, into: &buf)
        FfiConverterString.write(value.authorEmail, into: &buf)
        FfiConverterString.write(value.authorDate, into: &buf)
        FfiConverterString.write(value.committerName, into: &buf)
        FfiConverterString.write(value.committerEmail, into: &buf)
        FfiConverterString.write(value.committerDate, into: &buf)
        FfiConverterString.write(value.subject, into: &buf)
        FfiConverterString.write(value.body, into: &buf)
        FfiConverterSequenceString.write(value.parents, into: &buf)
        FfiConverterTypeSerieCommitKind.write(value.kind, into: &buf)
        FfiConverterSequenceTypeSerieRepositoryRef.write(value.refs, into: &buf)
    }
}

public func FfiConverterTypeSerieCommitSummary_lift(_ buf: RustBuffer) throws -> SerieCommitSummary {
    return try FfiConverterTypeSerieCommitSummary.lift(buf)
}

public func FfiConverterTypeSerieCommitSummary_lower(_ value: SerieCommitSummary) -> RustBuffer {
    return FfiConverterTypeSerieCommitSummary.lower(value)
}

public struct SerieRepositorySnapshot {
    public var path: String
    public var head: SerieRepositoryHead
    public var commits: [SerieCommitSummary]

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(path: String, head: SerieRepositoryHead, commits: [SerieCommitSummary]) {
        self.path = path
        self.head = head
        self.commits = commits
    }
}

extension SerieRepositorySnapshot: Equatable, Hashable {
    public static func == (lhs: SerieRepositorySnapshot, rhs: SerieRepositorySnapshot) -> Bool {
        if lhs.path != rhs.path {
            return false
        }
        if lhs.head != rhs.head {
            return false
        }
        if lhs.commits != rhs.commits {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(path)
        hasher.combine(head)
        hasher.combine(commits)
    }
}

public struct FfiConverterTypeSerieRepositorySnapshot: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SerieRepositorySnapshot {
        return
            try SerieRepositorySnapshot(
                path: FfiConverterString.read(from: &buf),
                head: FfiConverterTypeSerieRepositoryHead.read(from: &buf),
                commits: FfiConverterSequenceTypeSerieCommitSummary.read(from: &buf)
            )
    }

    public static func write(_ value: SerieRepositorySnapshot, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterTypeSerieRepositoryHead.write(value.head, into: &buf)
        FfiConverterSequenceTypeSerieCommitSummary.write(value.commits, into: &buf)
    }
}

public func FfiConverterTypeSerieRepositorySnapshot_lift(_ buf: RustBuffer) throws -> SerieRepositorySnapshot {
    return try FfiConverterTypeSerieRepositorySnapshot.lift(buf)
}

public func FfiConverterTypeSerieRepositorySnapshot_lower(_ value: SerieRepositorySnapshot) -> RustBuffer {
    return FfiConverterTypeSerieRepositorySnapshot.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SerieCommitKind {
    case commit
    case stash
}

public struct FfiConverterTypeSerieCommitKind: FfiConverterRustBuffer {
    typealias SwiftType = SerieCommitKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SerieCommitKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .commit

        case 2: return .stash

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SerieCommitKind, into buf: inout [UInt8]) {
        switch value {
        case .commit:
            writeInt(&buf, Int32(1))

        case .stash:
            writeInt(&buf, Int32(2))
        }
    }
}

public func FfiConverterTypeSerieCommitKind_lift(_ buf: RustBuffer) throws -> SerieCommitKind {
    return try FfiConverterTypeSerieCommitKind.lift(buf)
}

public func FfiConverterTypeSerieCommitKind_lower(_ value: SerieCommitKind) -> RustBuffer {
    return FfiConverterTypeSerieCommitKind.lower(value)
}

extension SerieCommitKind: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SerieCommitOrderType {
    case chrono
    case topo
}

public struct FfiConverterTypeSerieCommitOrderType: FfiConverterRustBuffer {
    typealias SwiftType = SerieCommitOrderType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SerieCommitOrderType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .chrono

        case 2: return .topo

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SerieCommitOrderType, into buf: inout [UInt8]) {
        switch value {
        case .chrono:
            writeInt(&buf, Int32(1))

        case .topo:
            writeInt(&buf, Int32(2))
        }
    }
}

public func FfiConverterTypeSerieCommitOrderType_lift(_ buf: RustBuffer) throws -> SerieCommitOrderType {
    return try FfiConverterTypeSerieCommitOrderType.lift(buf)
}

public func FfiConverterTypeSerieCommitOrderType_lower(_ value: SerieCommitOrderType) -> RustBuffer {
    return FfiConverterTypeSerieCommitOrderType.lower(value)
}

extension SerieCommitOrderType: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SerieFileChange {
    case add(path: String)
    case modify(path: String)
    case delete(path: String)
    case move(from: String, to: String)
}

public struct FfiConverterTypeSerieFileChange: FfiConverterRustBuffer {
    typealias SwiftType = SerieFileChange

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SerieFileChange {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .add(path: FfiConverterString.read(from: &buf))

        case 2: return try .modify(path: FfiConverterString.read(from: &buf))

        case 3: return try .delete(path: FfiConverterString.read(from: &buf))

        case 4: return try .move(from: FfiConverterString.read(from: &buf), to: FfiConverterString.read(from: &buf))

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SerieFileChange, into buf: inout [UInt8]) {
        switch value {
        case let .add(path):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(path, into: &buf)

        case let .modify(path):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(path, into: &buf)

        case let .delete(path):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(path, into: &buf)

        case let .move(from, to):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(from, into: &buf)
            FfiConverterString.write(to, into: &buf)
        }
    }
}

public func FfiConverterTypeSerieFileChange_lift(_ buf: RustBuffer) throws -> SerieFileChange {
    return try FfiConverterTypeSerieFileChange.lift(buf)
}

public func FfiConverterTypeSerieFileChange_lower(_ value: SerieFileChange) -> RustBuffer {
    return FfiConverterTypeSerieFileChange.lower(value)
}

extension SerieFileChange: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SerieRepositoryHead {
    case branch(name: String)
    case detached(target: String)
    case none
}

public struct FfiConverterTypeSerieRepositoryHead: FfiConverterRustBuffer {
    typealias SwiftType = SerieRepositoryHead

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SerieRepositoryHead {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .branch(name: FfiConverterString.read(from: &buf))

        case 2: return try .detached(target: FfiConverterString.read(from: &buf))

        case 3: return .none

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SerieRepositoryHead, into buf: inout [UInt8]) {
        switch value {
        case let .branch(name):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(name, into: &buf)

        case let .detached(target):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(target, into: &buf)

        case .none:
            writeInt(&buf, Int32(3))
        }
    }
}

public func FfiConverterTypeSerieRepositoryHead_lift(_ buf: RustBuffer) throws -> SerieRepositoryHead {
    return try FfiConverterTypeSerieRepositoryHead.lift(buf)
}

public func FfiConverterTypeSerieRepositoryHead_lower(_ value: SerieRepositoryHead) -> RustBuffer {
    return FfiConverterTypeSerieRepositoryHead.lower(value)
}

extension SerieRepositoryHead: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SerieRepositoryRef {
    case tag(name: String, target: String)
    case branch(name: String, target: String)
    case remoteBranch(name: String, target: String)
    case stash(name: String, message: String, target: String)
}

public struct FfiConverterTypeSerieRepositoryRef: FfiConverterRustBuffer {
    typealias SwiftType = SerieRepositoryRef

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SerieRepositoryRef {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .tag(name: FfiConverterString.read(from: &buf), target: FfiConverterString.read(from: &buf))

        case 2: return try .branch(name: FfiConverterString.read(from: &buf), target: FfiConverterString.read(from: &buf))

        case 3: return try .remoteBranch(name: FfiConverterString.read(from: &buf), target: FfiConverterString.read(from: &buf))

        case 4: return try .stash(name: FfiConverterString.read(from: &buf), message: FfiConverterString.read(from: &buf), target: FfiConverterString.read(from: &buf))

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SerieRepositoryRef, into buf: inout [UInt8]) {
        switch value {
        case let .tag(name, target):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(name, into: &buf)
            FfiConverterString.write(target, into: &buf)

        case let .branch(name, target):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(name, into: &buf)
            FfiConverterString.write(target, into: &buf)

        case let .remoteBranch(name, target):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(name, into: &buf)
            FfiConverterString.write(target, into: &buf)

        case let .stash(name, message, target):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(name, into: &buf)
            FfiConverterString.write(message, into: &buf)
            FfiConverterString.write(target, into: &buf)
        }
    }
}

public func FfiConverterTypeSerieRepositoryRef_lift(_ buf: RustBuffer) throws -> SerieRepositoryRef {
    return try FfiConverterTypeSerieRepositoryRef.lift(buf)
}

public func FfiConverterTypeSerieRepositoryRef_lower(_ value: SerieRepositoryRef) -> RustBuffer {
    return FfiConverterTypeSerieRepositoryRef.lower(value)
}

extension SerieRepositoryRef: Equatable, Hashable {}

private struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

private struct FfiConverterSequenceTypeSerieCommitSummary: FfiConverterRustBuffer {
    typealias SwiftType = [SerieCommitSummary]

    static func write(_ value: [SerieCommitSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSerieCommitSummary.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SerieCommitSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [SerieCommitSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeSerieCommitSummary.read(from: &buf))
        }
        return seq
    }
}

private struct FfiConverterSequenceTypeSerieFileChange: FfiConverterRustBuffer {
    typealias SwiftType = [SerieFileChange]

    static func write(_ value: [SerieFileChange], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSerieFileChange.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SerieFileChange] {
        let len: Int32 = try readInt(&buf)
        var seq = [SerieFileChange]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeSerieFileChange.read(from: &buf))
        }
        return seq
    }
}

private struct FfiConverterSequenceTypeSerieRepositoryRef: FfiConverterRustBuffer {
    typealias SwiftType = [SerieRepositoryRef]

    static func write(_ value: [SerieRepositoryRef], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSerieRepositoryRef.write(item, into: &buf)
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SerieRepositoryRef] {
        let len: Int32 = try readInt(&buf)
        var seq = [SerieRepositoryRef]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeSerieRepositoryRef.read(from: &buf))
        }
        return seq
    }
}

public func rustAdd(a: UInt32, b: UInt32) -> UInt32 {
    return try! FfiConverterUInt32.lift(try! rustCall {
        uniffi_rustylib_fn_func_rust_add(
            FfiConverterUInt32.lower(a),
            FfiConverterUInt32.lower(b), $0
        )
    })
}

public func rustHello() -> String {
    return try! FfiConverterString.lift(try! rustCall {
        uniffi_rustylib_fn_func_rust_hello($0)
    })
}

public func serieCommitDetail(path: String, commitHash: String) -> SerieCommitDetail {
    return try! FfiConverterTypeSerieCommitDetail.lift(try! rustCall {
        uniffi_rustylib_fn_func_serie_commit_detail(
            FfiConverterString.lower(path),
            FfiConverterString.lower(commitHash), $0
        )
    })
}

public func serieIsGitRepository(path: String) -> Bool {
    return try! FfiConverterBool.lift(try! rustCall {
        uniffi_rustylib_fn_func_serie_is_git_repository(
            FfiConverterString.lower(path), $0
        )
    })
}

public func serieRepositorySnapshot(path: String, maxCount: UInt32?, order: SerieCommitOrderType) -> SerieRepositorySnapshot {
    return try! FfiConverterTypeSerieRepositorySnapshot.lift(try! rustCall {
        uniffi_rustylib_fn_func_serie_repository_snapshot(
            FfiConverterString.lower(path),
            FfiConverterOptionUInt32.lower(maxCount),
            FfiConverterTypeSerieCommitOrderType.lower(order), $0
        )
    })
}

public func serieVersion() -> String {
    return try! FfiConverterString.lift(try! rustCall {
        uniffi_rustylib_fn_func_serie_version($0)
    })
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

/// Use a global variable to perform the versioning checks. Swift ensures that
/// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_rustylib_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_rustylib_checksum_func_rust_add() != 47653 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_rustylib_checksum_func_rust_hello() != 11814 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_rustylib_checksum_func_serie_commit_detail() != 28531 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_rustylib_checksum_func_serie_is_git_repository() != 22362 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_rustylib_checksum_func_serie_repository_snapshot() != 31465 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_rustylib_checksum_func_serie_version() != 22913 {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
